/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#222a3d",
        "on-tertiary-container": "#ffffff",
        "inverse-primary": "#0060ab",
        "secondary-fixed-dim": "#bcc7de",
        "tertiary-container": "#007eb4",
        "surface-variant": "#2d3449",
        "surface": "#0b1326",
        "surface-tint": "#a3c9ff",
        "surface-dim": "#0b1326",
        "on-secondary": "#263143",
        "on-surface-variant": "#c0c7d4",
        "primary-container": "#0078d4",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",
        "surface-bright": "#31394d",
        "on-primary": "#00315c",
        "on-tertiary-fixed-variant": "#004c6e",
        "on-primary-container": "#ffffff",
        "secondary": "#bcc7de",
        "on-surface": "#dae2fd",
        "inverse-on-surface": "#283044",
        "tertiary-fixed": "#c9e6ff",
        "primary-fixed": "#d3e3ff",
        "error-container": "#93000a",
        "surface-container-highest": "#2d3449",
        "secondary-container": "#3e495d",
        "tertiary-fixed-dim": "#89ceff",
        "on-secondary-fixed-variant": "#3c475a",
        "on-primary-fixed": "#001c39",
        "secondary-fixed": "#d8e3fb",
        "primary": "#a3c9ff",
        "on-tertiary-fixed": "#001e2f",
        "on-secondary-fixed": "#111c2d",
        "on-error": "#690005",
        "tertiary": "#89ceff",
        "on-background": "#dae2fd",
        "on-secondary-container": "#aeb9d0",
        "surface-container-lowest": "#060e20",
        "surface-container": "#171f33",
        "primary-fixed-dim": "#a3c9ff",
        "on-tertiary": "#00344d",
        "background": "#0b1326",
        "outline": "#8a919e",
        "on-primary-fixed-variant": "#004883",
        "outline-variant": "#404752",
        "surface-container-low": "#131b2e",
        "inverse-surface": "#dae2fd",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
